name: flutter_login_signup
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dio:
  multipart_request: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.5
  image_picker: ^0.6.7+9
  toast: ^0.1.5
  shared_preferences: 0.5.7
  load: ^0.1.6
  flutter_svg:
  dropdownfield:
  carousel_pro: ^1.0.0
  path_provider: 1.6.1
  jiffy:
  flutter_markdown:
  autocomplete_textfield:
  keyboard_visibility:
  social_share:
  image_cropper:
  simple_gesture_detector:
  firebase_messaging:
  flutter_local_notifications:
  device_info:

  form_field_validator:
  webview_flutter:
  url_launcher:






dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/progressBar.gif
    - assets/logo.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/name_icon.png
    - assets/username_icon.png
    - assets/dob_icon.png
    - assets/street_icon.png
    - assets/email_icon.png
    - assets/telephone_icon.png
    - assets/city_icon.png
    - assets/mobile_icon.png
    - assets/occupation_icon.png
    - assets/dob_icon.png
    - assets/username_icon.png
    - assets/country_icon.png
    - assets/blood_icon.png
    - assets/gender_icon.png
    - assets/news_icon.png
    - assets/blood_request_icon.png
    - assets/tourism_icon.png
    - assets/success_stories_icon.png
    - assets/business_directory_icon.png
    - assets/local_products_icon.png
    - assets/events_icon.png
    - assets/linkedin_icon.png
    - assets/password_icon.png
    - assets/confirm_password_icon.png
    - assets/marital_status_icon.png
    - assets/home/local_products.png
    - assets/social_media/pinterest.png
    - assets/social_media/whatsapp.png
    - assets/social_media/facebook.png
    - assets/social_media/instagram.png
    - assets/notification/notification.png
    - assets/tourism/icons/local_restaurants.png
    - assets/tourism/icons/places_to_go.png
    - assets/tourism/icons/places_to_stay.png
    - assets/tourism/icons/things_to_do.png
    - assets/blood_request/icons/blood_type.png
    - assets/blood_request/icons/contact_number.png
    - assets/blood_request/icons/contact_person.png
    - assets/blood_request/icons/hospital_name.png
    - assets/blood_request/icons/patient_name.png
    - assets/blood_request/banners/blood_banner.png
    - assets/event/heart_red.png
    - assets/event/heart_white.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
